when:
  - event: push
    branch: master

steps:
  - name: publish
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: arnochen/chatwise-searxng
      dockerfile: ./Dockerfile
      platforms: linux/amd64
      auto_tag: true
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password